#!/usr/bin/env bash
# Use of awk

print_domain()
{
    # if 2 argv does not exist
    if [[ -z "$2" ]]
    then
	dig www."$1" | awk 'f;/ANSWER SECTION:/{f=1}' | head -n 1 | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
	dig lb-01."$1" | awk 'f;/ANSWER SECTION:/{f=1}' | head -n 1 | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
	dig web-01."$1" | awk 'f;/ANSWER SECTION:/{f=1}' | head -n 1 | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
	dig web-02."$1" | awk 'f;/ANSWER SECTION:/{f=1}' | head -n 1 | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
    # 2 argv exists
    else
	printf "The subdomain %s is a " "$2"
	dig "$2"."$1" |  awk 'f;/ANSWER SECTION:/{f=1}' | head -n 1 | awk '{print $4 " record and points to " $5}'
    fi
}
print_domain "$1" "$2"
