#!/usr/bin/env bash
# uses ssh to connect to your server using the private key ~/.ssh/holberton with the user ubuntu
if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1"@"$3":"$2":~/ -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
fi