#!/usr/bin/env bash
# installs a nginx with redirection
apt-get update
apt-get -y install nginx
sed -i "19i return 301 35.196.2.249/redirect_me;" /etc/nginx/sites-available/default
service nginx restart