#!/usr/bin/env bash
# Prints Holberton school using a while loop
num=1
while((num <= 10))
do
   if [ $num -eq 4 ]
    then
        echo "bad luck"
    elif [ $num -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
   (( num=num+1 ))
done