#!/usr/bin/env bash
# Prints superstitious numbers using case in bash
hours=0
minutes=1
while (( hours<= 12 ))
do
    echo "Hour: $hours"
    minutes=1
    while (( minutes <= 59))
    do
        echo $minutes
        (( minutes=minutes+1 ))
    done
    (( hours=hours+1 ))
done