#!/usr/bin/env bash
# creates a ssh key pair
#!/usr/bin/env bash
# uses ssh to connect to your server using the private key ~/.ssh/holberton with the user ubuntu
ssh-keygen -b 4096 -t rsa -N betty -f holberton